### PR TITLE
return invalid_client in oauth2 error code

### LINKED ISSUE #2545: Error response code not compliant to RFC 6749
### What version of UAA are you running?

76.22.0 (latest)

### How are you deploying the UAA?

as part of a commercial Cloud Foundry distribution

### What did you do?

I am trying to generate access tokens using the token endpoint - `{authenticationUrl}/oauth/token`

### What did you expect to see? What goal are you trying to achieve with the UAA?

with invalid client credentials, the error response was expected to be as follows:
- Code: 401 Unauthorized
- Body:
  **- “error”: “invalid_grant”**
  - “error_description”:  “Bad credentials”

### What did you see instead?

with invalid client credentials, the error response is as follows:

- Code: 401 Unauthorized
- Body:
  **- “error”: “unauthorized”**
  - “error_description”:  “Bad credentials”

**Question 1**: in [RFC6749 section 5.2](https://www.rfc-editor.org/rfc/rfc6749#section-5.2) -  “unauthorized” is not in the list of allowed ‘error codes’. We should use an error response code from this available list of codes.
**Question 2**: in [RFC6749 section 5.2](https://www.rfc-editor.org/rfc/rfc6749#section-5.2) - suggests a 400 unless specified otherwise. Any reason why we use a 401?

### PR DESCRIPTION
**Pull request by strehle**
return invalid_client in oauth2 error response body

Fix for issue #2545

### CODE REVIEW

**Comment by strehle** [comment]
alternative PR to https://github.com/cloudfoundry/uaa/pull/2575

**Comment by hsinn0** [comment]
> alternative PR to #2575

What does this mean? Do you want reviewers pick one between this PR and #2575, which apparently is in progress?

**Comment by strehle** [comment]
> What does this mean? Do you want reviewers pick one between this PR and #2575, which apparently is in progress?
Yes I have created the new PR to decide which value should be returned

**Review by hsinn0 — APPROVED** [review]
Approving, with the expectation this change to be mentioned in the release note as discussed during our sync-up meeting.

**Pull request merged**
