### PR TITLE
feat: support refresh token rotation

### LINKED ISSUE #1448: Feature request: Rotation of refresh tokens for public clients
The current OAuth drafts with security best practices for Single Page Applications / Browser-based Apps ask for refresh token rotation, in case refresh tokens are issued to public clients.
See:

- https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-07#section-4 
- https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-6.1

As of now (v74.28.0), refresh token rotation is not supported by CF UAA.
Are there already plans to support this in CF UAA (e.g., as a feature that can be enabled/configured per client)?

### PR DESCRIPTION
**Pull request by strehle**
Fix for issue #1448 

- switch: jwt.token.refresh.rotate
- default off / false
- Needed for OAuth 2.1 compliance, https://oauth.net/2.1/. This feature supports Refresh tokens one-time use.
- Needs https://github.com/cloudfoundry/uaa-release/pull/392 , add jwt.token.refresh.rotate in uaa sepc of uaa-release

### CODE REVIEW

**Comment by strehle** [comment]
Sonar result
https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=1969

**Review by bruce-ricard — APPROVED** [review]

**Comment by strehle** [comment]
@bruce-ricard Thanks for approving.
I rebased, refactored , added docs information and after all , wanted simply to know (because of discussions)

Should we stay with parameter name refreshTokenRotate or should it be more like refreshTokenSingleUse / refreshTokenOneTimeUse ?
If you have no thoughts on the name, then I think we should stay we it,

**Comment by bruce-ricard** [comment]
I'm fine with the current naming. It's not perfect, but hopefully future readers will understand.

**Comment by strehle** [comment]
> 
@bruce-ricard 
So you have a proposal for a better name?

**Pull request merged**
