### PR TITLE
Initial support for Facebook external IdP using signed_request (develop)

### PR DESCRIPTION
**Pull request by dre2901**
Here is basic support for Facebook as external IdP using their implementation of signed_request (based on OAuth).
Corresponding login configuration:
```
      facebook:
        type: oauth2.0
        authUrl: https://www.facebook.com/dialog/oauth
        tokenUrl: https://graph.facebook.com/oauth/access_token
        responseType: signed_request
        issuer: https://www.facebook.com
        scopes:
          - public_profile
          - email
        linkText: Login with Facebook
        showLinkText: true
        addShadowUserOnLogin: true
        relyingPartyId: <redacted>
        relyingPartySecret: <redacted>
        skipSslValidation: true
        attributeMappings:
          user_name: user_id
```

### CODE REVIEW

**Comment by sreetummidi** [comment]
@dre2901 Can you please provide tests for this pull request

**Comment by sreetummidi** [comment]
@dre2901 Can you please provide the CLA for Cloud Foundry.  Please see the comment above about the CLA

**Comment by fhanik** [comment]
Closing pull request. CLA and tests are missing. Will implement feature separately.

**Comment by dre2901** [comment]
CLA was filed and confirmed by Chris Clark already two months ago on 6th of June

**Comment by fhanik** [comment]
Thank you.

**Comment by fhanik** [comment]
Closing and reopening the PR will trigger the bot check for CLA

**Pull request closed without merging**
