### PR TITLE
Fixed query string (first param should be appended using ? instead of &) - fix #600

### LINKED ISSUE #600: Implicit flow: incorrect redirect URL (query params)
When using the implicit flow (in the browser) by redirecting the user to: 

http://localhost:7001/uaa/oauth/authorize?response_type=token&client_id=XXX&redirect_uri=http%3A%2F%2Flocalhost%3A8100%2F%23%2Flogin

The user gets redirected back after successful login to:

http://localhost:8100/#/login&token_type=bearer&access_token=eyJhbGci...

As the query parameters are added with an & instead of ? the authenticated application cannot get the query parameters correctly. Shouldn't the first query param be appended with an ? and only the following params with &

So a correct URL would be:

http://localhost:8100/#/login?token_type=bearer&access_token=eyJhbGci...

### PR DESCRIPTION
**Pull request by maust**
This will fix #600 

Would be interesting to know why nobody yet had this issue, as it seems that it is in there since 2015

Furthermore I removed boolean fragment as it is always true. If this is not wanted let me know and I revert it.

### CODE REVIEW

**Comment by fhanik** [comment]
Thank you @maust for your contribution.

We use TDD, test driven development, for all our code.
What we expect is two commits.

The first commit adds a test that tests the new or changed functionality. This test should fail(red) since the functionality has not been added. Basically, the first commit shows, `this is how I want things to work` and since the test fails, it clearly doesn't work that way today.

The second commit adds/changes the functionality of the code. and the test suite is green(passes)

By quickly glancing at the contribution, without tests, it is hard to judge it to be correct or complete.

Are you able to add tests to your PR?

**Comment by maust** [comment]
@fhanik Sure, I updated the existing test. If I need to do something else let me know.

Build seems to be good now, only the default test failed because the build stalled. Not sure how I can retstart it.

**Comment by fhanik** [comment]
Did you mean to close this issue?

**Comment by maust** [comment]
Shouldn't I? Submitting the CLA was confirmed -> "Once you've publicized your membership, one of the owners of this repository can close and reopen this pull request, and dreddbot will take another look."

**Comment by maust** [comment]
Two builds failed because the connection to LDAP failed. As I understand it is not caused by my changes.

**Comment by fhanik** [comment]
no worries, we're still debugging that flakiness. I restarted the two jobs

**Comment by sreetummidi** [comment]
To be reviewed

**Comment by fhanik** [comment]
Requesting feedback on #600 before merging. Temporary branch at https://github.com/cloudfoundry/uaa/commit/c24a51bde9287996a8ad5b1eb5050469b5899964

**Comment by fhanik** [comment]
OAuth 2 Spec shows an example as 

    HTTP/1.1 302 Found
    Location: http://example.com/cb#access_token=2YotnFZFEjr1zCsicMWpAA
               &state=xyz&token_type=example&expires_in=3600

No `?` is needed in the fragment. Parameters in the fragment are delimited by `&`
We believe the UAA to be compliant with the spec.

Please reopen if you feel we have made this decision in error.

Reference
https://tools.ietf.org/html/rfc6749#section-4.2.2

**Pull request closed without merging**
