### PR TITLE
Sql server support

### PR DESCRIPTION
**Pull request by andyliuliming**

### CODE REVIEW

**Comment by andyliuliming** [comment]
@fhaniK the failure seems not due to my change.

**Comment by fhanik** [comment]
@andyliuliming I'm currently working on this PR
According to the [MS documentation](https://msdn.microsoft.com/en-us/library/ms378878(v=sql.110).aspx) the SQL Server JDBC driver handles BIT to boolean conversion. Is the `BooleanValueAdapter` necessary?

**Comment by andyliuliming** [comment]
@fhanik from testing result, yes, it's necessary.

**Comment by fhanik** [comment]
hi @andyliuliming - Thank you so much for this contribution.
We left your original commit intact, and then reworked the contribution so that our CI tests on Travis would have enough coverage and pass. https://travis-ci.org/cloudfoundry/uaa/builds/190773587

Per Cloud Foundry Foundation policy, we changed the Copyright from Microsoft to Cloud Foundry Foundation

This was the merge that concludes this pull request
https://github.com/cloudfoundry/uaa/commit/8d7ccd33344db3c06c3fd62998f86d91de91ba47

**Comment by fhanik** [comment]
@andyliuliming we did remove the boolean value adapter. All tests pass without it.

If there is a need for it, please provide a test case for us. Thank you

**Pull request closed without merging**
