### PR TITLE
Feature/redirect uri path traversal

### PR DESCRIPTION
**Pull request by taitzariel**
The tracker story id for this issue is #166884661

fixes the following redirect_uri vulnerabilities (for code and implicit grant types).

1 - double url-encoded request

registered redirect_uri = http://example.com/foo
requested redirect_uri = http://example.com/foo/%252e./bar
attacker's site = http://example.com/bar
tomcat receives the request with redirect_uri parameter http://example.com/foo/%252e./bar and url decodes %25 to %
uaa receives http://example.com/foo/%2e./bar and returns it to the victim's browser
browser url decodes %2e to a dot (.) to obtain http://example.com/foo/../bar which the browser normalizes to http://example.com//bar and sends the attacker the authorization code or token.

2 - registered path contains wildcard

registered redirect_uri = http://example.com/foo/**
requested redirect_uri = http://example.com/foo/../bar
attacker's site = http://example.com/bar

This attack succeeds even without url encoding the dots.
When the registered path contains wildcards, the uaa does not normalize the request path.

### CODE REVIEW

**Comment by taitzariel** [comment]
@andrewedstrom Hi Andrew, Please can someone from your team review this?

**Comment by taitzariel** [comment]
@joshuatcasey Hi Joshua, Please can you review this pull request?

**Comment by strehle** [comment]
@taitzariel I know a long time ago, but if you rebase your PR I would review it and prepare a merge

**Comment by taitzariel** [comment]
Hi Markus,
We are honoured that you are considering accepting this PR.
Many sleepless nights have passed awaiting this treasured moment.
Please coordinate with Shimi (cc'd) regarding the rebase, as I am no longer
working on UAA.

Ariel

**Comment by strehle** [comment]
Ok, problem is, that you should rebase this PR first before we disccuss further and if another colleague takes it then you can also open a new PR

**Comment by taitzariel** [comment]
Hi Markus,

We are extremely pleased that you will consider this PR once it has been
rebased.
Please correspond with Shimi (cc'd) and not with me as I am no longer
working on UAA (the excitement that one day my pull requests may be
considered was too much for me to bear).

Ariel


בתאריך יום ה׳, 15 ביולי 2021 ב-19:01 מאת Markus Strehle <
***@***.***>:

**Pull request merged**
