### PR TITLE
[token] allow for configurable inclusion of typ header

### PR DESCRIPTION
**Pull request by tony-kerz**
proposal to address: https://github.com/cloudfoundry/uaa/issues/270

relies on: https://github.com/spring-projects/spring-security-oauth/pull/659

### CODE REVIEW

**Comment by fhanik** [comment]
We'll have to wait for Spring Security release, we don't include snapshots, since that means the build is not reproducible when the snapshot changes.

**Comment by tony-kerz** [comment]
yep, just dropped it as a place-holder. in the mean time, feel free to provide any feedback on this or spring-security commits. tx!

**Comment by cromark** [comment]
@fhanik , @dsyer has updated https://github.com/spring-projects/spring-security-oauth ( see  [commit](https://github.com/spring-projects/spring-security-oauth/commit/3efc6b3b4885af9ec867085bc769ce470e2a5258) ). 

All that is required is to update [shared_versions.gradle](https://github.com/cloudfoundry/uaa/blob/master/shared_versions.gradle) with `springSecurityJwtVersion = '1.0.4.RELEASE'`

**Comment by staylor14** [comment]
Current UAA adds in `typ` header. We have for now included the header code directly in the UAA, because we require the `kid` header too

    {
      "alg": "RS256",
      "kid": "legacy",
      "typ": "JWT"
    }

**Pull request closed without merging**
