### PR TITLE
For cloudfoundry/uaa#666

### PR DESCRIPTION
**Pull request by kannangce**
*Problem:* Currently the `environment.resolvePlaceholders` is called only for the type string. In reality the values are of type Map, List.
*Fix:* Added logic to resolve the values.
*Reference:* https://github.com/cloudfoundry/uaa/issues/666

### CODE REVIEW

**Comment by DennisDenuto** [comment]
@kannangce This PR currently [does not compile](https://travis-ci.org/cloudfoundry/uaa/jobs/392091431) 
```
:cloudfoundry-identity-server:compileJava FAILED
:cloudfoundry-identity-server:compileJava took 11922ms
```

**Comment by kannangce** [comment]
@DennisDenuto  Sorry for the missed `git add`. Now made sure everything got committed and pushed. It builds and runs in my local.

On the testing part, I tried parameterizing the value of `oauth.clients.*.redirect-uri`  from `uaa.yml` and passed the value in environment variable. Which got picked up and the client created with the respective values from the environment variable. Before the fix that was not working.

**Comment by kannangce** [comment]
@DennisDenuto Any other comments that I need to check?

**Comment by DennisDenuto** [comment]
Hi @kannangce Thanks for explaining how to use this new env config logic. 

Can you please provide some tests for the new logic in `EnvironmentMapFactoryBean`. You can add unit tests here: https://github.com/cloudfoundry/uaa/blob/31a6dfba592acad3652b24ecdbb3fb7c6c0eac78/server/src/test/java/org/cloudfoundry/identity/uaa/config/EnvironmentMapFactoryBeanTests.java#L32-L32

Some tests to add might be (these are pseudocode examples):
# "happy case tests"
1.1) a property that is a map
given: System.setProperty("some_env", "some_env_value");
input map: 
```
fake-client:
  key1: ${some_env}
```
expected output:
```
fake-client:
  key1: some_env_value
```

1.2) a property that is a map
input map: 
```
fake-client:
  key1: ${spam}
```
expected output:
```
fake-client:
  key1: ${spam}
```

2.1) a property that is a list
given: System.setProperty("some_env", "some_env_value");
input list: 
```
- fake-client: ${some_env}
```
expected output:
```
- fake-client: some_env_value
```

2.2) a property that is a list
input list: 
```
- fake-client: ${spam}
```
expected output:
```
- fake-client: ${spam}
```

# error cases:
1.1) a property that is a map with null values
input map: 
```
fake-client:
  key1: null
```
expected output:
```
fake-client:
  key1: null
```

1.2) a property that is a list with null values
input list: 
```
[ ${some_env}, null ]
```
expected output:
```
[ ${some_env}, null ]
```

**Comment by kannangce** [comment]
@DennisDenuto Thanks for the suggestion!

Added and verified the tests.

The below are the details of the tests that I added,

**`testPlaceholderResolutionFor{X}Value`** - To test the resolution of the placeholder from System environment.
**`testPlaceholderResolutionForNoEnv{X}Value`** - To test the case when no environment for the resolvable placeholder present.
**`testPlaceholderResolutionFor{X}NullValue`** - To test the null values in the values.

Where **{X}** can be a simple value, List or Map.

Please verify and let me know if things are good.

**Comment by DennisDenuto** [comment]
Nice. LGTM.
@jhamon WDYT? Can you think of any security concerns with regards to this change?

**Comment by shamus** [comment]
Closing due to inactivity.

**Pull request closed without merging**
