### PR TITLE
Remove hardcoded localhost in login it

### PR DESCRIPTION
**Pull request by amiri-ge**
Just testing the waters by removing a hard-coded reference to localhost in LoginIT.java

### CODE REVIEW

**Comment by fhanik** [comment]
@amiri-ge did you submit your CLA?

**Comment by amiri-ge** [comment]
@fhanik I should be covered under the GE Software CLA. FYI I made my membership to that organization public in profile as per your guidelines.

**Comment by fhanik** [comment]
Will be merged in using 93c5c349c79bbe648986c50198f2b901c5bf11e9
That way we avoid all the extra commits that this PR has.

**Comment by amiri-ge** [comment]
@fhanik Thanks. BTW, for future pull requests, is it necessary to create an issue first then submit the request or is it OK to document the issue in the pull request comments?

**Comment by fhanik** [comment]
It's ok to directly create a pull requests, that is sufficient

**Pull request closed without merging**
