### PR TITLE
prevent lock situation during update of last_logon_success_time on postgres

### PR DESCRIPTION
**Pull request by tack-sap**
PR for #1983 

As mentioned in the Issue description, this is how we resolved the lock situation in our own UAA-based service.

In a normal situation the behavior of this code is identical. Only in case the lock cannot be granted during the update statement, the update would be skipped. But this would mean another process is currently trying an update on the same row, maybe with a few milliseconds difference in last logon time, but still there is an update. As we still have all the audit events of all those parallel requests, we concluded that the stability of the UAA should be more important than keeping the last logon time redundantly in the DB for every user.

Like announced in the issue description this is only changing the behavior for postgresql, as this is where we saw the problem and this is also where we already were able to validate that the fix is working and not breaking stuff.

As the behavior from the outside is the same in a normal use case, the current ITs are already covering the new code (when executed against postgres).

### CODE REVIEW

**Comment by tack-sap** [comment]
Failing IT seems to be unrelated to my changes, as I see the same errors locally against a clean develop branch now

**Review by strehle — COMMENTED** [review]
in past similar vendor sql related problems were solved with LimitSqlAdapter, so why not rename this to something like VendorSqlAdapter and add the update SQL into this interface next to limit SQLs 

Sonar should be green before merge
https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=1984

**Comment by strehle** [comment]
@torsten-sap FYI please check if you agree on a solution where we use an interface class instead of a custom SQL inside the call

You want stay with our code, ok but Sonar needs to be Green that is what we ensure before merge

**Comment by torsten-sap** [comment]
@tack-sap, @strehle and myself decided to go for PR https://github.com/cloudfoundry/uaa/pull/1993 to solve issue https://github.com/cloudfoundry/uaa/issues/1983. Thus, closing this PR.

**Pull request closed without merging**
