### PR TITLE
Bump snakeyaml from 1.33 to 2.0

### PR DESCRIPTION
**Pull request by strehle**
spring framework read:
https://github.com/spring-projects/spring-framework/issues/30097
https://github.com/spring-projects/spring-framework/pull/30048
https://github.com/advisories/GHSA-mjmj-j48q-9wg2

jackson 2.14.2 or higher needs to be used because only there 
https://github.com/FasterXML/jackson-dataformats-text/commit/9f822fb3fb248784f72708c4a30a8bddf9a0dc16

### CODE REVIEW

**Comment by strehle** [comment]
With next Spring-Boot Version we can do the update

**Comment by strehle** [comment]
after merge of https://github.com/cloudfoundry/uaa/pull/2237, re-base this PR 
and new spring boot the upgrade should be possible , see 
https://github.com/spring-projects/spring-boot/issues/34405#issuecomment-1479808747

**Comment by wberry-godaddy** [comment]
any chance this could be ported to older versions of Spring as well?

**Comment by strehle** [comment]
> any chance this could be ported to older versions of Spring as well?

you are here in the wrong project, we only consume spring projects but you have to ask https://github.com/spring-projects

**Review by Tallicia — APPROVED** [review]
Clear comments, LGTM

**Pull request merged**
