### PR TITLE
Changed validation query for hsqldb

### PR DESCRIPTION
**Pull request by nmalpallstate**
About the bug-fix
- change validationQuery for HSQLDB
- test case to prove that the validationQuery works

### CODE REVIEW

**Comment by fhanik** [comment]
Closing. No response. No CLA.

**Comment by nmalpallstate** [comment]
Hi Filip,

There is a CLA signed by the Allstate itself with CF org.

Nilesh

**Comment by fhanik** [comment]
@nmalpallstate Thank you for this request. We just upgraded to the latest tomcat-jdbc pool, and are now seeing the same issue you may have experienced. 

We're merging this PR in right now.

**Comment by sreetummidi** [comment]
@fhanik is this merged as part of a different story?
Can we close this.

**Comment by sreetummidi** [comment]
@fhanik Can we close this

**Comment by fhanik** [comment]
@sreetummidi yes, we can close it

**Pull request closed without merging**
