### PR TITLE
fix: update k8s to go 1.20

### PR DESCRIPTION
**Pull request by Tallicia**
updated and has updated with go mod tidy.

[#185619304]

@peterhaochen47

### CODE REVIEW

**Comment by hsinn0** [comment]
The change itself, which has the one-line change in `go.mod` is as expected. However, there is something wrong with the commit message.

> has updated with go mod vendor

`go mod vendor` would have created vendor folder as it did not exist yet. However, `vendor` folder is not a part of the commit and it should not be as we do not need/want that for this go module. Just doing `go mod tidy` was enough for this change. I suggest to remove "go mod vendor" from the commit message.
See https://go.dev/ref/mod#vendoring.

**Review by hsinn0 — CHANGES_REQUESTED** [review]
See the comment regarding the commit message.

**Comment by Tallicia** [comment]
@hsinn0 The requested changes have been made.

**Comment by hsinn0** [comment]
I see the PR comment updated. However, the commit message was not. Isn't the commit message the one added as commit message after "Rebase and merge"?

**Review by hsinn0 — APPROVED** [review]

**Pull request merged**
