### PR TITLE
Feature/custom attributes

### PR DESCRIPTION
**Pull request by bsekar**
Extending UAA schema to allow custom attributes based on discussion [here](https://github.com/cloudfoundry/uaa/issues/1480#issuecomment-878926436)

### CODE REVIEW

**Comment by bsekar** [comment]
We're aware of the missing CLA. We're working with our legal team to have it done

**Comment by strehle** [comment]
I went through code and about users db enhancement. Why dont you use and extend user_info and info blob field which is also json as far as I see ?
To me it makes sense to (re-)use this schema and store custom attributes in info field as json similar then you do it

**Comment by bsekar** [comment]
Thanks @strehle for reviewing this. Reusing the [userAttributes](https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/user/UserInfo.java#L30) in UserInfo was our initial option as well, but for the following reasons we decided to put it in ScimUser itself.


1. If one wants to update custom attributes on the user, currently there is no API to set the same. The only operation on userInfo is the OIDC standard `GET /userinfo`
1. UserInfo seems to be used when UAA is federating with external IdP (SAML etc) and we wanted this to be available natively as a first class property, when UAA acts as the user store/source of truth.

**Comment by bsekar** [comment]
@strehle Did you get a chance to review the above comment?

**Comment by strehle** [comment]
> Did you get a chance to review the above comment?

partly but uaa pipeline is red and release build is blocked because vmware colleagues are blocked.
So I need them for their thoughts.

Right now I can say that we (SAP) have often trouble because of high DB load and users table is one of the hotspots and thus I do not prefere to extend it, but rather have custom attributes in another table so that not all selects for user do a fetch of all values . Most of the scenarios wont need it therefore it should not be in main users db.
@br @peterhaochen47  your thoughts ?

**Comment by strehle** [comment]
added other maintainers and request their feedback. 
So I wont block this if other say yes, but if nobody answer I would like to seperate the attribute persistency into another db and then I will accept it , as mentioned I recommend exiting user_info

**Review by torsten-sap — COMMENTED** [review]
I agree with @strehle that custom attributes should not be persisted in the users table. The reasons were already mentioned.

**Pull request closed without merging**
