### PR TITLE
Feature/support custom redirect uri schemes

### PR DESCRIPTION
**Pull request by RoopGuron**

### CODE REVIEW

**Comment by jhamon** [comment]
Could you give some background on the use-case and motivation for this change?

**Comment by Bitty9** [comment]
We have teams which would like to redirect to a native mobile app using custom schemes which are registered with the phone OS after authentication. With the redirect uri enforcement changes, the ability to redirect to custom schemes was lost.  See https://tools.ietf.org/html/rfc6749#section-9 for more details.

**Comment by aashah** [comment]
Hm, It'd be nice to look into better ways of validating incoming URIs than expanding the list of Regex patterns. Some languages provide standardized URI regexps (downside being we'd have to upgrade the lib/language if there's an issue) that would probably have allowed your use case. 

Something to look into as well...

**Comment by Bitty9** [comment]
@aashah The reason we are using a custom regex pattern is because UAA is more restrictive than traditional uris about what is allowed for a client. For example, a redirect uri can have a * in the subdomain but not in the domain. Similarly, the scheme can have http* to match both http and https. This comes into play when a client is created because a client may provide a redirect_uri which is an ant-style path pattern. Do you have a specific library in mind which would accommodate these types of restrictions without turning into writing our own custom regex?

**Comment by sreetummidi** [comment]
@RoopGuron Where are the custom URLs whitelist of allowed patterns set?

**Comment by RoopGuron** [comment]
@sreetummidi 
Change only modifies the pattern applied to the **_scheme_** part of the **_URI pattern_** being applied in the `UaaUrlUtils.java.allowedRedirectUriPattern`
The **_scheme_** pattern `^(([a-zA-Z][a-zA-Z0-9+-.]*)|(http(\\*|s)?)):`conforms to the RFC Uniform Resource Identifier (URI) section on scheme: https://tools.ietf.org/html/rfc3986#section-3.1

As per the examples of Custom URLs that would satisfy this would be as follows:
```
           "ftp://ftp.is.co.za/rfc/rfc1808.txt",
            "cool-app://example.com",
            "org.cloudfoundry.identity://mobile-windows-app.com/view",
            "org+cloudfoundry+identity://mobile-ios-app.com/view",
            "org-cl0udfoundry-identity://mobile-android-app.com/view"
         "http://localhost",
        "http://localhost:8080",
        "http://localhost:8080/uaa",
        "http://valid.com",
        "http://sub.valid.com",
        "http://valid.com/with/path",
        "https://subsub.sub.valid.com/**",
        "https://valid.com/path/*/path",
        "http://sub.valid.com/*/with/path**",
        "http*://sub.valid.com/*/with/path**",
        "http*://*.valid.com/*/with/path**",
        "http://*.valid.com/*/with/path**",
        "https://*.valid.com/*/with/path**",
        "https://*.*.valid.com/*/with/path**",
        "http://sub*.valid.com/*/with/path**",
        "http://*.domain.com",
        "http://username:password@some.server.com",
        "http://username:password@some.server.com/path"
```

**Comment by Bitty9** [comment]
Last commit includes a wildcard in redirect uri for #679

**Comment by sreetummidi** [comment]
@RoopGuron I was initially under the impression that we are whitelisting known set of mobile/iot protocols (I am not sure if any such list exists). This PR is adding support for any kind of text passing as a protocol which is fairly open. Is the protocol part the name of the mobile application?

**Comment by RoopGuron** [comment]
@sreetumidi the protocol part(custom scheme) is not necessarily the name of the native/mobile app, but is associated with one particular mobile app. Please refer to comment by @bitty9 where there is a link to the rfc section addressing this.    As potentially there could be multiple mobile applications using oauth2 authorization grant flow to get refresh tokens, there could be multiple custom schemes, each scheme name has to conform to the uri scheme BMW pattern.

**Comment by ilipkind** [comment]
The latest discussion on this pull request can be found here: https://github.com/cloudfoundry/uaa/issues/679

**Comment by sreetummidi** [comment]
Closing in lieu of https://www.pivotaltracker.com/story/show/154735792

**Pull request closed without merging**
