### PR TITLE
Add support for HTTP Redirect binding for UAA as SAML IDP

### PR DESCRIPTION
**Pull request by RoopGuron**
Signed-off-by: Bharath <bharath.sekar@ge.com>

### CODE REVIEW

**Comment by sreetummidi** [comment]
Review and merge

**Comment by fhanik** [comment]
@RoopGuron 

**PLEASE COMPLETE**

Thanks for submitting this pull request!

All pull request submitters and commit authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA (individual or corporate).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

If you are confident that you're covered under a Corporate CLA, please make sure you've publicized your membership in the appropriate Github Org, per these instructions.

Once you've publicized your membership, one of the owners of this repository can close and reopen this pull request, and dreddbot will take another look.

**Comment by fhanik** [comment]
@RoopGuron @bsekar 

Question: Is there a test that uses the redirect binding? I see tests around the metadata containing it, but I can't see changes that would pertain to the actual integration test using the new binding.

**Comment by RoopGuron** [comment]
@fhanik 
SamlLoginWithLocalIdpIT.java integration test
testWebSSOProfileWithRedirectPostSamlIntegration uses the new binding line number 562.
It is a new integration test for the WebssoProfile Redirect/POST.

**Comment by thecardkid** [comment]
@RoopGuron Can we get a test with a mock assertion that uses the correct binding. The current integration test will succeed either way and doesn't test the new feature explicitly. Thank you

**Pull request merged**
