### PR TITLE
Modified CorsFilter to support XHR for whitelisted request URIs and origins.

### PR DESCRIPTION
**Pull request by amiri-ge**
Please see https://github.com/cloudfoundry/uaa/issues/173 for reference. This pull request is to provide more context for that issue.

### CODE REVIEW

**Comment by fhanik** [comment]
Thanks, testing this should be pretty straight forward using MockMvc

We define all our filters in the Spring configuration files

https://github.com/cloudfoundry/uaa/blob/feature/revert_password_policy_defaults/uaa/src/main/webapp/WEB-INF/spring-servlet.xml#L86-86

This allows us to do full web requests without ever starting up a server that requires web.xml

I would also use org.springframework.util.StringUtils instead of the HsqlDB library, where you have the method hasText and isEmpty to achieve what you need. The HsqlDB library dependency should only exist from the perspective of having an in memory DB, not as class libraries used by us.

**Comment by amiri-ge** [comment]
Good catch on the StringUtil. Actually, I believe we meant to use apache commons StringUtils but got burned by the IDE's autocomplete.

As for the testing. It's not the server side that worries me so much as the browser side. Ultimately, it's the browser that enforces CORS based on the headers provided by the server. The real question is how can we create automated testing for browser side CORS behavior similar to say: http://test-cors.org ?

**Comment by fhanik** [comment]
I believe it is out of scope for the UAA to test whether the browser enforces CORS or not. Our responsibility is that with given input we produce output, and we should be able to test that by providing test cases for everything that we build. Both happy day cases and error cases.

**Comment by amiri-ge** [comment]
@fhanik Understood. So if we cleaned this up and added some MockMvc test cases is this something you would be interested in?

**Comment by fhanik** [comment]
absolutely, the only thing I'd ask for is

1. Put filter in the Spring config
2. Provide a reference for the rules being implemented (ie, what are you basing your implementation on)
3. Mock mvc tests

after that there won't be any issue merging the PR

**Comment by amiri-ge** [comment]
@fhanik I'm running into an baffling problem with the MockMvc tests. Here are the facts.
1. All integration tests pass when I run "gradle integrationTest". Except 3 tests which are annotated as Ignore and are therefore skipped.
2. The CORS filter feature seems to work just fine when testing from the browser using test-cors.org
3. The MockMvc tests that I added work just fine when I run them from within Eclipse.

Here's the problem: When I "gradle test" my MockMvc tests are skipped entirely. There is no indication in the report or in the gradle output (using --debug) as to why they are being skipped.

Any idea what might cause this? I'm going to update the pull request so you can take a look at the code.

**Comment by fhanik** [comment]
When you run gradlew test it skips the individual tests, but runs them all in a suite (so that the app context is only created once for all MVC tests)

https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/DefaultConfigurationTestSuite.java#L50-L70

The individual test detects if it is running in the suite

https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/InjectedMockContextTest.java#L29-29

So if you wish to run all MVC tests fast in your IDE, then you would run the DefaultConfigurationTestSuite

**Comment by fhanik** [comment]
BTW, this is where your CorsFilter is already defined, not in uiSecurity, which only covers a small portion of the requests, and not all of them (see my earlier comments in this thread)

https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/webapp/WEB-INF/spring-servlet.xml#L58-L96

**Comment by amiri-ge** [comment]
@fhanik I see your point about redefining the bean. Unfortunately, my understanding of Spring is too limited to know where I could put the filter in a way that it would cover both the login and uaa endpoints. I'm open to suggestions.

**Comment by fhanik** [comment]
@amiri-ge - remove your definition of the bean, and remove the insertion into uiSecurity.

The CorsFilter is already there, it was there before you started coding. All you are doing is adding features to it. So you don't have to change Spring XML files for your PR at all. Hope that makes sense.

**Comment by amiri-ge** [comment]
@fhanik - It makes perfect sense. I had failed to see the import for classpath:login-ui.xml in spring-servlet.xml. Thanks for the help.

**Comment by amiri-ge** [comment]
The implementation was based on guidance from:
http://www.w3.org/TR/cors/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

I included this information in the comment for the CorsFilter class as well.

**Pull request merged**
