### PR TITLE
update dependency org.seleniumhq.selenium:selenium-java to v4.18.1

### PR DESCRIPTION
**Pull request by strehle**
https://www.selenium.dev/downloads/

https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG

### CODE REVIEW

**Comment by strehle** [comment]
The selenium driver is mainly used in UI tests ... you worked in past with SAML tests so update should help in order to prevent issues with webdriver

**Comment by strehle** [comment]
@swalchemist do you want to review it ? it is no code change but simply allows to update selenium more often

**Review by hsinn0 — APPROVED** [review]

**Comment by hsinn0** [comment]
It is a good change as the two dependency's versions are different.

**Review by swalchemist — APPROVED** [review]
Seems that the first commit broke the unit tests, and the second commit fixes them. More context in the commit message would help future developers understand what happened. Is selenium-http-jdk-client:4.18.1 incompatible with selenium-java 4.18.1, or with our code somewhere?

**Comment by strehle** [comment]
> selenium-http-jdk-client

no there is simply no http client with same version, happed by acciddent that 4.13.x had same version

**Pull request merged**
