### PR TITLE
feature: allow setting SameSite on X-Uaa-Csrf cookie

### PR DESCRIPTION
**Pull request by mikeroda**

### CODE REVIEW

**Comment by strehle** [comment]
@mikeroda can you please describe how you want use this feature. I see a test, but there is no external configuration option, so to me you can only use this if you have our own UAA as fork but call the api in your forked UAA.

**Review by strehle — APPROVED** [review]
ok for me

**Comment by mikeroda** [comment]
@strehle that is correct. This is useful for projects that fork UAA and call the API to change the SameSite configuration on the X-Uaa-Csrf cookie. Might seem trivial but is a lot more convenient than extending the class to add the setter method.

**Comment by strehle** [comment]
> @strehle that is correct. This is useful for projects that fork UAA and call the API to change the SameSite configuration on the X-Uaa-Csrf cookie. Might seem trivial but is a lot more convenient than extending the class to add the setter method.

Ok, I am fine with

**Pull request merged**
