### PR TITLE
Fix circular view path errors on login

### PR DESCRIPTION
**Pull request by mikeroda**
The login endpoint should return text/html by default if no Accept header is specified, or if the client specifies */*. However, requests to UAA with an unexpected media type in the Accept header can get redirected to the login page and will result in a 500 status code and the following error:

Circular view path [login]: would dispatch back to the current handler URL [/uaa/login] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)

This is because the loginForHtml endpoint accepts */* but when spring goes to render the page it can't find an appropriate view. The fix to this is to take an additional parameter with the Accept media types
and check to see if it is compatible.

### CODE REVIEW

**Comment by fhanik** [comment]
@mikeroda Thanks for the PR - there are some failing test cases

https://api.travis-ci.org/jobs/197102923/log.txt?deansi=true

**Comment by mikeroda** [comment]
Is there a way to rerun the build? Looks like an unrelated failure.

**Comment by fhanik** [comment]
Restarted it for you
https://travis-ci.org/cloudfoundry/uaa/builds/197166789

**Comment by fhanik** [comment]
We do get false negatives quite often....test suite has turned into somewhat of a behemoth

**Comment by sreetummidi** [comment]
Additional tests need to be added to validate the response code

**Comment by fhanik** [comment]
Closing via https://github.com/cloudfoundry/uaa/commit/ceb8b72299cadc4b64bd1fc872f8527d7e3da404

**Pull request closed without merging**
