### PR TITLE
Updating Readme & Adding LDAP Setup Option

### PR DESCRIPTION
**Pull request by xandroc**
Update Readme with instructions for configuring UAA and LDAP for local development

### CODE REVIEW

**Comment by Tallicia** [comment]
3 things:
1 - Having instructions on docker cleanup (and reruns for dockerfile changes in support/debug moments) is always a nice reminder.
2 - Did I not get co-author credit? right now I am having to build my contribution record t be able to resume release duties and others, so every commit counts.
3 - The uaa.yml changes that are spaced shifting commented lines seems superfluous and distracting from the core changes.

**Comment by xandroc** [comment]
`1 - Having instructions on docker cleanup (and reruns for dockerfile changes in support/debug moments) is always a nice reminder.`

Good point, I'll add some instruction on bringing down the container and cleaning up the volume

`2 - Did I not get co-author credit? right now I am having to build my contribution record t be able to resume release duties and others, so every commit counts.`

You should have been listed as a co-author, my git-duet must be on the fritz I'll make the update.

`3 - The uaa.yml changes that are spaced shifting commented lines seems superfluous and distracting from the core changes.`

Great catch! Not sure how those got introduced, I'll remove them

**Comment by xandroc** [comment]
> 3 things: 1 - Having instructions on docker cleanup (and reruns for dockerfile changes in support/debug moments) is always a nice reminder. 2 - Did I not get co-author credit? right now I am having to build my contribution record t be able to resume release duties and others, so every commit counts. 3 - The uaa.yml changes that are spaced shifting commented lines seems superfluous and distracting from the core changes.

@Tallicia updates are complete

**Comment by Tallicia** [comment]
This PR is closed, is there another or does this need to be reopened?

**Pull request merged**
