### PR TITLE
Feature/client secret policy

### PR DESCRIPTION
**Pull request by 6palace**
adding a client secret policy similar to the user password policy.

### CODE REVIEW

**Comment by fhanik** [comment]
Thank you we will review.

**Comment by 6palace** [comment]
Hi Filip, a test we wrote seems to have broken when we rebased onto the develop branch, we will fix then re-push commit by commit to comply with tdd requirements.

**Comment by 6palace** [comment]
Hi @fhanik is this still in the pull request queue?

**Comment by sreetummidi** [comment]
To be merged

**Pull request merged**
