### PR TITLE
Modified UaaHttpRequestUtils to build an HTTP client that uses the system proxy settings.

### PR DESCRIPTION
**Pull request by DarioAmiri**
See [`issue 411`](https://github.com/cloudfoundry/uaa/issues/411)

### CODE REVIEW

**Comment by amiri-ge** [comment]
@fhanik Took me a while but here it is:
- Fix for OIDC get token request behind a proxy
- Single commit
- All tests pass
- I can confirm this works behind our proxy

Few comments
- UAA uses different HttpClient APIs across the code which makes it hard to unify the code for handling proxy issues. Ideally, the code would migrate toward a single reusable solution. I did not undertake this because the code changes would have been significant.
- The presence of a skipSslValidation flag is worrisome to me. In my experience, features like this are often abused. Why not import your trusted certificates to the java cacerts store or use a custom trust store or get a free certificate from [let's encrypt](https://letsencrypt.org)? 
- The skipSslValidation mechanism that is in place replaces the rest template in XOAuthAuthenticationManager for every request made because the skipSslValidation flag comes from a parameter. This seems wasteful.

**Comment by fhanik** [comment]
This story is in progress
https://github.com/cloudfoundry/uaa/commit/871e92511fe6876b928b4ed4ef74749d6f027f4c

**Comment by fhanik** [comment]
Completed by https://github.com/cloudfoundry/uaa/commit/dd8372657bdce317702e6c83ec6d2da981dc5864

**Comment by fhanik** [comment]
Added proxy validation tests.

**Pull request closed without merging**
