### PR TITLE
Add flyway dependency and use interface for tokenServices

### PR DESCRIPTION
**Pull request by mikeroda**
Pull request to add flyway dependency and use an interface for tokenServices

### CODE REVIEW

**Comment by fhanik** [comment]
I'm confused about the flyway commit, what does it address?

**Comment by mikeroda** [comment]
The SecurityFilterChainPostProcessor does actually depend on flyway migration so the database tables are created before this bean is initialized. Right now it is getting luck with the bean initialization order but this change will ensure the correct order of dependencies. I can go into more specifics of how I made it fail if necessary but this is more of a cleanup item.

**Comment by fhanik** [comment]
the security filter chain depends on other beans that depend on other beans that depend on the jdbctemplate - wouldn't it therefor be more prudent that the jdbc template depended on flyway?

https://github.com/cloudfoundry/uaa/blob/develop/common/src/main/resources/spring/data-source.xml#L84-84

and thus, your dependency would be resolved.

**Comment by mikeroda** [comment]
Good point. Let me rework the commit that way.

**Pull request closed without merging**
