### PR TITLE
Fix OIDC well-known endpoint to be in compliance with spec

### PR DESCRIPTION
**Pull request by bsekar**
This change provides a fix for issue #652 
As per the [spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation), `issuer` value returned by the config should be identical to the `<issuer_url>` used to obtain the config (ex: `<issuer_url>/.well-known/openid-configuration`) and the `iss` claim in the id_token

### CODE REVIEW

**Comment by fhanik** [comment]
This PR changes the endpoint from 

    /.well-known/openid-configuration

to

    /oauth/token/.well-known/openid-configuration

That is a breaking change we can't accept. Instead we want this PR to change

    /.well-known/openid-configuration

to

    /.well-known/openid-configuration
    /oauth/token/.well-known/openid-configuration

This should also limit the changes to existing test cases, and just introduce new test cases.

_unless you have a compelling reason why the old endpoint shouldn't continue to function_

**Comment by bsekar** [comment]
@fhanik Fair enough. I will update the PR

**Comment by sreetummidi** [comment]
@bsekar Are you able to update the PR based on comments from @fhanik
We would like to release this in the upcoming version aka 4.6.0

**Comment by fhanik** [comment]
I can fix it. https://github.com/cloudfoundry/uaa/commit/4b8e9a039d2d97b49d6268ae31c59b016bb6ef5c

**Comment by bsekar** [comment]
Thanks @fhanik @sreetummidi

**Comment by maplain** [comment]
Is this going to be included in release 4.6? I'm still blocked by this when trying to make it work with k8s. thx.

**Comment by jhamon** [comment]
@maplain Yes, this work is in `develop` which means it should be included in the next release.

**Comment by maplain** [comment]
Hi, @jhamon thanks for the reply. I did try to do ./gradlew build both on prerelease/4.6.0 and develop, but they all failed a few tests. Could you please give me some advice on how to try this out in deployment? Any help is appreciated!

**Comment by jhamon** [comment]
@maplain Have you ever run the tests successfully before? Or is this your first time running them?

I can give more useful advice if you can provide more detail about the failures you're seeing.

**Comment by fhanik** [comment]
Some of the SSL tests require certificates to be generated. The [.travis.yml](https://github.com/cloudfoundry/uaa/blob/develop/.travis.yml#L148-L150) file really helps to understand what our test suites do

**Comment by maplain** [comment]
@jhamon yes, this is my first time. What I did are basically just: pull corresponding branch and run a './gradlew build'.
logs are here: [log.tar.gz](https://github.com/cloudfoundry/uaa/files/1252561/log.tar.gz).
Failed tests are:
```
DefaultSecurityContextAccessorTests. zoneAdminClientIsAdmin
DefaultSecurityContextAccessorTests. zoneAdminUserIsAdmin
DefaultSecurityContextAccessorTests. zoneAdminUserIsNotAdmin_BecauseOriginIsNotUaa
```
all because of NullPointerException. Looks like I may need to provide something here?

**Comment by fhanik** [comment]
@maplain ok, those tests should work 100% every time unless you broke them yourself.

Make sure you run Java 8, and that JAVA_HOME is correctly set, then 
  
    ./scripts/travis/install-ldap-certs.sh
    ./gradlew test

and it should fly through.

**Comment by maplain** [comment]
@fhanik thanks. this is what I got:
```
kubo@jumphost:~/uaa$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
kubo@jumphost:~/uaa$ echo $JAVA_HOME
/usr/lib/jvm/java-1.8.0-openjdk-amd64
kubo@jumphost:~/uaa$  ./scripts/travis/install-ldap-certs.sh
Generating keystore file for server.
Exporting certificate for client
Certificate stored in file </tmp/valid-self-signed-ldap-cert.jks.crt>
Generating keystore file for server.
Exporting certificate for client
Certificate stored in file </tmp/expired-self-signed-ldap-cert.jks.crt>
Installing /tmp/expired-self-signed-ldap-cert.jks.crt with alias expired-self-signed-ldap-cert
Installing /tmp/valid-self-signed-ldap-cert.jks.crt with alias valid-self-signed-ldap-cert
kubo@jumphost:~/uaa$ ./gradlew test
:compileJava UP-TO-DATE
:compileJava took 2ms
:processResources UP-TO-DATE
:processResources took 1ms
:classes UP-TO-DATE
:classes took 0ms
:compileTestJava UP-TO-DATE
:compileTestJava took 1ms
:processTestResources UP-TO-DATE
:processTestResources took 1ms
:testClasses UP-TO-DATE
................................................
................................................
org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests > zoneAdminUserIsNotAdmin_BecauseOriginIsNotUaa FAILED
    java.lang.NullPointerException at DefaultSecurityContextAccessorTests.java:120

org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests > zoneAdminUserIsAdmin FAILED
    java.lang.NullPointerException at DefaultSecurityContextAccessorTests.java:101

org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests > zoneAdminClientIsAdmin FAILED
    java.lang.NullPointerException at DefaultSecurityContextAccessorTests.java:134
org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests took 36ms
org.cloudfoundry.identity.uaa.security.X509ExpiryCheckingTrustManagerTest took 22ms
org.cloudfoundry.identity.uaa.security.CsrfAwareEntryPointAndDeniedHandlerTest took 6ms
Gradle Test Executor 3 took 7ms
Gradle Test Run :cloudfoundry-identity-server:test took 164ms

2432 tests completed, 3 failed, 13 skipped
:cloudfoundry-identity-server:test FAILED
:cloudfoundry-identity-server:test took 149176ms

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloudfoundry-identity-server:test'.
> There were failing tests. See the report at: file:///home/kubo/uaa/server/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by fhanik** [comment]
@maplain this is a clean branch?

Let's try this

    git stash
    git checkout develop
    git pull
    git clean -fd
    ./gradlew clean
    ./scripts/travis/install-ldap-certs.sh
    ./gradlew test

ie, you must try this on a clean working branch. What we are trying to make sure is that you have a passing test suite *before* you make any changes. That way you know the changes you put in are either passing or not.

**Comment by maplain** [comment]
@fhanik I understand. I changed nothing. Like I said above, I just want to have a build that I can deploy since current latest version 4.5 still has this .well-known/openid-configuration bug blocking integration with k8s.

```
kubo@jumphost:~/uaa$ git stash
No local changes to save
kubo@jumphost:~/uaa$ git checkout develop
Already on 'develop'
Your branch is up-to-date with 'origin/develop'.
kubo@jumphost:~/uaa$ git pull
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/cloudfoundry/uaa
   629b4b6..d593f29  develop    -> origin/develop
Updating 629b4b6..d593f29
Fast-forward
 uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/FacebookLoginIT.java   | 15 +++++++++++----
 uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/util/IntegrationTestUtils.java |  9 ++++++++-
 2 files changed, 19 insertions(+), 5 deletions(-)
kubo@jumphost:~/uaa$ git clean -fd
kubo@jumphost:~/uaa$ ./gradlew clean
:clean
:clean took 1ms
:cloudfoundry-identity-client-lib:clean
:cloudfoundry-identity-client-lib:clean took 2ms
:cloudfoundry-identity-model:clean
:cloudfoundry-identity-model:clean took 5ms
:cloudfoundry-identity-samples:clean UP-TO-DATE
:cloudfoundry-identity-samples:clean took 0ms
:cloudfoundry-identity-server:clean
:cloudfoundry-identity-server:clean took 64ms
:cloudfoundry-identity-uaa:clean UP-TO-DATE
:cloudfoundry-identity-uaa:clean took 0ms
:cloudfoundry-identity-samples:cloudfoundry-identity-api:clean UP-TO-DATE
:cloudfoundry-identity-samples:cloudfoundry-identity-api:clean took 0ms
:cloudfoundry-identity-samples:cloudfoundry-identity-app:clean UP-TO-DATE
:cloudfoundry-identity-samples:cloudfoundry-identity-app:clean took 1ms

BUILD SUCCESSFUL

Total time: 0.907 secs
Task timings:
Test timings:
kubo@jumphost:~/uaa$ ./scripts/travis/install-ldap-certs.sh
Generating keystore file for server.
Exporting certificate for client
Certificate stored in file </tmp/valid-self-signed-ldap-cert.jks.crt>
Generating keystore file for server.
Exporting certificate for client
Certificate stored in file </tmp/expired-self-signed-ldap-cert.jks.crt>
Certificate already installed. Replacing it
Certificate already installed. Replacing it
kubo@jumphost:~/uaa$ ./gradlew test
:compileJava UP-TO-DATE
:compileJava took 0ms
:processResources UP-TO-DATE
:processResources took 0ms
.....
org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests > zoneAdminUserIsNotAdmin_BecauseOriginIsNotUaa FAILED
    java.lang.NullPointerException at DefaultSecurityContextAccessorTests.java:120

org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests > zoneAdminUserIsAdmin FAILED
    java.lang.NullPointerException at DefaultSecurityContextAccessorTests.java:101

org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests > zoneAdminClientIsAdmin FAILED
    java.lang.NullPointerException at DefaultSecurityContextAccessorTests.java:134
org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests took 21ms
org.cloudfoundry.identity.uaa.security.X509ExpiryCheckingTrustManagerTest took 21ms
org.cloudfoundry.identity.uaa.security.CsrfAwareEntryPointAndDeniedHandlerTest took 5ms
Gradle Test Executor 3 took 5ms
Gradle Test Run :cloudfoundry-identity-server:test took 165ms

2432 tests completed, 3 failed, 13 skipped
:cloudfoundry-identity-server:test FAILED
:cloudfoundry-identity-server:test took 151511ms

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloudfoundry-identity-server:test'.
> There were failing tests. See the report at: file:///home/kubo/uaa/server/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 41.056 secs
Task timings:
    745ms  :cloudfoundry-identity-client-lib:test
   1867ms  :cloudfoundry-identity-model:test
   1284ms  :cloudfoundry-identity-server:compileJava
   4479ms  :cloudfoundry-identity-server:compileTestJava
 151511ms  :cloudfoundry-identity-server:test
Test timings:
   5270ms  org.cloudfoundry.identity.uaa.scim.bootstrap.ScimGroupBootstrapTests
   5491ms  org.cloudfoundry.identity.uaa.provider.saml.LoginSamlAuthenticationProviderTests
   6004ms  org.cloudfoundry.identity.uaa.client.ClientAdminBootstrapTests
   8886ms  org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimUserProvisioningTests
  20788ms  org.cloudfoundry.identity.uaa.scim.endpoints.ScimGroupEndpointsTests
  21044ms  org.cloudfoundry.identity.uaa.util.CachingPasswordEncoderTest
```

**Comment by maplain** [comment]
or I shouldn't do './gradlew build' at all?
my goal is to make uaa work with k8s.
my problem is version 45 still has '/.well-known/openid-configuration' endpoint, but issuer being '/oauth/token' so you will see 
```
E0825 18:27:30.380495   18382 oidc.go:178] oidc authenticator: failed to fetch provider discovery data: missing required field subject_types_supported
```
in kube-apiserver's log. 

```
kubo@jumphost:~/kubo-deployment$ curl --cacert ./ca.pem -H "Accept: application/json"  https://192.168.112.3:8443/login | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   372    0   372    0     0   3275      0 --:--:-- --:--:-- --:--:--  3292
{
  "app": {
    "version": "4.5.0"
  },
  "links": {
    "uaa": "https://192.168.112.3:8443",
    "passwd": "/forgot_password",
    "login": "https://192.168.112.3:8443",
    "register": "/create_account"
  },
  "zone_name": "uaa",
  "entityID": "192.168.112.3:8443",
  "commit_id": "df80f63",
  "idpDefinitions": {},
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ]
  },
  "timestamp": "2017-07-21T15:45:01-0700"
}
```
```
kubo@jumphost:~/kubo-deployment$ curl --cacert ./ca.pem  https://192.168.112.3:8443/.well-known/openid-configuration | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1141    0  1141    0     0  11291      0 --:--:-- --:--:-- --:--:-- 11410
{
  "issuer": "https://192.168.112.3:8443/oauth/token",
  "authorization_endpoint": "https://192.168.112.3:8443/oauth/authorize",
  "token_endpoint": "https://192.168.112.3:8443/oauth/token",
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "token_endpoint_auth_signing_alg_values_supported": [
    "RS256",
    "HS256"
  ],
  "userinfo_endpoint": "https://192.168.112.3:8443/userinfo",
  "jwks_uri": "https://192.168.112.3:8443/token_keys",
  "scopes_supported": [
    "openid",
    "profile",
    "email",
    "phone",
    "roles",
    "user_attributes"
  ],
  "response_types_supported": [
    "code",
    "code id_token",
    "id_token",
    "token id_token"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256",
    "HS256"
  ],
  "id_token_encryption_alg_values_supported": [
    "none"
  ],
  "claim_types_supported": [
    "normal"
  ],
  "claims_supported": [
    "sub",
    "user_name",
    "origin",
    "iss",
    "auth_time",
    "amr",
    "acr",
    "client_id",
    "aud",
    "zid",
    "grant_type",
    "user_id",
    "azp",
    "scope",
    "exp",
    "iat",
    "jti",
    "rev_sig",
    "cid",
    "given_name",
    "family_name",
    "phone_number",
    "email"
  ],
  "claims_parameter_supported": false,
  "service_documentation": "http://docs.cloudfoundry.org/api/uaa/",
  "ui_locales_supported": [
    "en-US"
  ]
}
kubo@jumphost:~/kubo-deployment$ curl --cacert ./ca.pem  https://192.168.112.3:8443/oauth/token | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   108    0   108    0     0   1047      0 --:--:-- --:--:-- --:--:--  1048
{
  "error": "unauthorized",
  "error_description": "An Authentication object was not found in the SecurityContext"
}
kubo@jumphost:~/kubo-deployment$ curl --cacert ./ca.pem  https://192.168.112.3:8443/oauth/token/.well-known/openid-configuration | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   108    0   108    0     0   1089      0 --:--:-- --:--:-- --:--:--  1090
{
  "error": "unauthorized",
  "error_description": "An Authentication object was not found in the SecurityContext"
}
```

**Comment by maplain** [comment]
The uaa I'm using is:
```
  value:
    name: uaa
    version: "45"
    url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/uaa-45-ubuntu-trusty-3445.2-20170822-204123-42127651-20170822204129.tgz
    sha1: 41cb1ea7c1dca2cc8c4a815eb498a163321c3965
```

**Comment by fhanik** [comment]
@maplain 

Let us know if file:///home/kubo/uaa/server/build/reports/tests/test/index.html has a deeper stack trace.

If not, then you're test is failing on 

    assertTrue(new DefaultSecurityContextAccessor().isAdmin());

that means the code 

    new DefaultSecurityContextAccessor()

returns `null`

if this is the case, you have a botched Java runtime installed. This should obviously never happen. Install a new JDK and then clean you `~/.gradle` caches and try again

**Comment by fhanik** [comment]
{
      "error": "unauthorized",
      "error_description": "An Authentication object was not found in
the SecurityContext"
    }


oh wow, this is something completely different. Let me look into this

Filip

**Comment by maplain** [comment]
@fhanik thanks a lot! here is the log. 
[log.tar.gz](https://github.com/cloudfoundry/uaa/files/1252716/log.tar.gz)
at the same time, I'll reinstall jdk and try again.

**Comment by fhanik** [comment]
@maplain JDK is probably fine, this is your actual error
```
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at org.cloudfoundry.identity.uaa.security.ContextSensitiveOAuth2SecurityExpressionMethods.replaceContext(ContextSensitiveOAuth2SecurityExpressionMethods.java:39)
	at org.cloudfoundry.identity.uaa.security.ContextSensitiveOAuth2SecurityExpressionMethods.replaceContext(ContextSensitiveOAuth2SecurityExpressionMethods.java:48)
	at org.cloudfoundry.identity.uaa.security.ContextSensitiveOAuth2SecurityExpressionMethods.hasAnyScope(ContextSensitiveOAuth2SecurityExpressionMethods.java:79)
	at org.springframework.security.oauth2.provider.expression.OAuth2SecurityExpressionMethods.hasScope(OAuth2SecurityExpressionMethods.java:106)
	at org.cloudfoundry.identity.uaa.security.ContextSensitiveOAuth2SecurityExpressionMethods.hasScopeInAuthZone(ContextSensitiveOAuth2SecurityExpressionMethods.java:88)
	at org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessor.isAdmin(DefaultSecurityContextAccessor.java:85)
	at org.cloudfoundry.identity.uaa.security.DefaultSecurityContextAccessorTests.zoneAdminClientIsAdmin(DefaultSecurityContextAccessorTests.java:134)
```

**Comment by fhanik** [comment]
Ok. so we have two problems

https://login.run.pivotal.io/oauth/token/.well-known/openid-configuration is asking for username/password. this is a high priority for us to investigate. 

and then you're unable to run the test suite for a strange reason.

**Comment by fhanik** [comment]
@maplain mystery solved

https://login.run.pivotal.io/.well-known/openid-configuration

the current OIDC discovery endpoint is 
/.well-known/openid-configuration

the 
/oauth/token/.well-known/openid-configuration
is not yet available in a release. you will have to wait for that to come out.

**Comment by maplain** [comment]
@fhanik thanks for looking into this. 
Isn't this the problem this PR(where our discussion happens) tries to address? I understand you have made changes to make /oauth/token/.well-known/openid-configuration available and I saw this change in develop and prerelease/4.6.0 branches, but not in 4.5 release.

so here comes why I was trying to build on develop. Because I was trying to get a 'self built release' that incorporates your changes mentioned above, thus I can deploy an uaa with '/oauth/token/.well-known/openid-configuration' enabled and to further verify k8s can successfully talk to uaa.

BTW, if you don't mind, may I ask the planned release date for 4.6?

Thanks again!

**Comment by fhanik** [comment]
this error

    {
      "error": "unauthorized",
      "error_description": "An Authentication object was not found in the SecurityContext"
    }

shows that you are trying to access and endpoint that doesn't exist.

if you want to build your own release, that is super simple

    ./gradlew assemble

then deploy the WAR file in `uaa/build/libs` to your web server

The answer to why your tests fail is still a myster

**Comment by maplain** [comment]
@fhanik ok. I'm using bosh to deploy it. so I'm not clear how to tell bosh to use that WAR file. or maybe I should look into uaa-release. probably need to read some documentation firstly. anyway, really appreciate your help. and my tests, yeah, that is weird..

**Comment by fhanik** [comment]
Here is how we create, finalize and upload a bosh release to bosh.io
https://github.com/cloudfoundry/uaa-release/blob/develop/scripts/perform-release.sh

In a nutshell, one command called

   bosh create release

yields your stuff. so in `uaa-release` you would bump the UAA submodule to `develop`

**Comment by maplain** [comment]
cool. will look into that.

**Pull request closed without merging**
