### PR TITLE
Check zone id

### PR DESCRIPTION
**Pull request by strehle**
After discussions in https://github.com/cloudfoundry/uaa/pull/2606

Add null checks to improve robustness in this dao

add more tests to cover all edge cases

https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=2617

### CODE REVIEW

**Review by klaus-sap — APPROVED** [review]
looks good to me

**Comment by strehle** [comment]
@swalchemist This is a small refactoring in preparation of a pr from @klaus-sap .

Return now an exception before asking JDBC (or DB) about null for a zone.
EmptyResultDataAccessException("Zone id cannot be null", 1);

**Comment by tack-sap** [comment]
@strehle currently the methods do not throw EmptyResultDataAccessException, but only ZoneDoesNotExistException. Would this maybe be a better Exception to throw, as this is something the calling classes may already expect?

**Comment by strehle** [comment]
> @strehle currently the methods do not throw EmptyResultDataAccessException, but only ZoneDoesNotExistException. Would this maybe be a better Exception to throw, as this is something the calling classes may already expect?

ok

**Review by tack-sap — APPROVED** [review]
LGTM

**Pull request merged**
