### PR TITLE
Upgrade to boot 3.0

### PR DESCRIPTION
**Pull request by rpau**
Hi, 

This is an experiment running an automatic upgrade to adopt Spring Boot 3.0 using Tanzu Spring Application Advisor. It is still work in progress. Some of the learnings we are accumulating for this example are:

* This project can't be upgraded to boot 3.0 until spring-security-saml-extensions are not migrated to Spring security. https://spring.io/blog/2020/09/22/spring-security-saml-extensions-1-x-eol-on-october-6-2021 .

* On the other hand, looks like you are using spring-security-saml 1.0.x instead of 2.0.x, which uses Spring security 5.2.x. This means, that in our end, the application requires the following upgrade plan for upgrading until boot 3.0.

Step 1:
    *  Upgrade spring-security-saml 1.0.x to 2.0.x
Step 2:
    * Replace spring-security-saml 2.0.x for spring-security 5.8.x
Step 3:
    * Upgrade spring-framework from 5.3.x to 6.0.x
    * Upgrade spring-security from 5.8.x to 6.0.x
    * Upgrade spring-ldap from 2.4.x to 3.0.x
    * Upgrade spring-boot from 2.7.x to 3.0.x
    * Upgrade spring-retry from 1.3.x to 2.0.x

* The dependency versions can't be upgraded in the way they are defined, but looks like the main reason is to overwrite the dependency resolution. This means that dependency versions should be changed manually.

### CODE REVIEW

**Comment by strehle** [comment]
FYI: https://github.com/cloudfoundry/uaa/issues/2561 , https://github.com/cloudfoundry/uaa/issues/2115

**Comment by strehle** [comment]
@rpau we will do the upgrade soon, now all legacy parts are removed

**Comment by rpau** [comment]
I am sending a PR at this moment.

**Comment by rpau** [comment]
https://github.com/cloudfoundry/uaa/pull/3171

**Pull request closed without merging**
