### PR TITLE
Fix/multiple instance startup

### LINKED ISSUE #498: Running multiple instances may result in single instance startup failure
Running a multi-instance app of uaa sometimes results in two instances running ScimGroupBootstrap at the same time, causing one of the instances failing to start with attached stacktrace. Note the IncorrectResultSizeDataAccessException happening in ScimGroupProvisioning.

`ERROR --- DispatcherServlet: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scimGroupBootstrap' defined in ServletContext resource [/WEB-INF/spring/scim-endpoints.xml]: Invocation of init method failed; nested exception is org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
ERROR --- DispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
ERROR --- DispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.web.RecognizeFailureDispatcherServlet.init(RecognizeFailureDispatcherServlet.java:56)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1140)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1027)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5038)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5348)
ERROR --- DispatcherServlet: 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
ERROR --- DispatcherServlet: 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
ERROR --- DispatcherServlet: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ERROR --- DispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
ERROR --- DispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
ERROR --- DispatcherServlet: 	at java.lang.Thread.run(Thread.java:745)
ERROR --- DispatcherServlet: Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:239)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:217)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:53)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimGroupBootstrap.afterPropertiesSet(ScimGroupBootstrap.java:190)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
ERROR --- DispatcherServlet: 	... 33 more
ERROR --- RecognizeFailureDispatcherServlet: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scimGroupBootstrap' defined in ServletContext resource [/WEB-INF/spring/scim-endpoints.xml]: Invocation of init method failed; nested exception is org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
ERROR --- RecognizeFailureDispatcherServlet: 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.web.RecognizeFailureDispatcherServlet.init(RecognizeFailureDispatcherServlet.java:56)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1227)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1140)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1027)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5038)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5348)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.lang.Thread.run(Thread.java:745)
ERROR --- RecognizeFailureDispatcherServlet: Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:239)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:217)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:53)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimGroupBootstrap.afterPropertiesSet(ScimGroupBootstrap.java:190)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
ERROR --- RecognizeFailureDispatcherServlet: 	... 33 more
`

### PR DESCRIPTION
**Pull request by 6palace**
fixes #498

### CODE REVIEW

**Comment by sreetummidi** [comment]
@6palace Can we do this in a more generic fashion for any object managed via API (Users, Groups, Clients, Zones, IDPs).  This looks like a generic version check to me.

**Comment by 6palace** [comment]
@sreetummidi that is true, it is quite possible we are missing version checking on other APIs. However, the bootstrap/provisioning/configurator structure is very different for every object type. Other Bootstraps may also listen for updates and operations from REST, but ScimGroupBootstrap is only used on UAA startup to update default groups from the configuration. More importantly groups seems to be the only flow which causes the startup issues. We can widen the net and add/verify version checking on all APIs, but for the scope of this issue in particular we should separate that into a separate pull request.

**Comment by sreetummidi** [comment]
To be reviewed

**Comment by cbguder** [comment]
@6palace it looks like the new test fails when this is rebased on develop. Please rebase, fix the test and re-submit.

**Comment by 6palace** [comment]
@cbguder I see this has been merged, do I still need rebase and re-submit? Did you guys fix the test failure?

**Pull request merged**
